version: '3'
services:
  app:
    container_name: devel_dashboard
    build:
      context: ../../
      dockerfile: containers/devel/Dockerfile
    env_file: dashboard.env
    ports:
      - 5000:5000
    command: /entrypoint.sh
    volumes:
      - ../../:/dashboard
      - ${DASH_ARCHIVE:-.:/archive}
      - ${DASH_CONFIG:-.:/config}
      - logs:/logs
  postgres:
    env_file: database.env
    container_name: devel_postgres
    image: postgres:13
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  logs:
