version: '3'
services:
  app:
    env_file: dashboard.env
    image: tigrlab/dashboard:0.1
    ports:
      - 5000:5000
    command: /entrypoint.sh
    volumes:
      - YOUR_DATA_PATH_HERE:/archive
      - YOUR_CONFIG_PATH_HERE:/config
      - logs:/logs
  postgres:
    env_file: database.env
    container_name: dash_postgres
    image: postgres:12.8
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  logs:
