version: '3'
services:
  app:
    container_name: dashboard
    image: tigrlab/dashboard:0.2.1
    env_file: ../dashboard.env
    ports:
      - 5000:5000
    command: /entrypoint.sh
    volumes:
      - ${DASH_ARCHIVE:-.}:/archive
      - ${DASH_CONFIG:-.}:/config
      - logs:/logs
  postgres:
    env_file: ../database.env
    container_name: dash_postgres
    image: postgres:13
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  logs:
