name: Build docs and push to pages

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
    types: [opened, synchronize, reopened]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d
      - name: Build docs
        run: docker exec -t devel_dashboard /bin/bash -c "sphinx-build dashboard/docs dashboard/docs/_build"
      - name: Repeat build in case non-deterministic build issue arose in last step
        run: docker exec -t devel_dashboard /bin/bash -c "sphinx-build dashboard/docs dashboard/docs/_build"
      - name: Add .nojekyll file to build folder
        run: sudo touch docs/_build/.nojekyll
      - name: Deploy docs if the branch has updated
        if: github.event == "push"
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/_build
      - name: Stop containers
        if: always()
        run: cd containers/devel && docker-compose down
