name: Run unit tests

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
    types: [opened, edited]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d
      - name: Run tests
        run: |
          docker exec -t devel_dashboard pytest -v dashboard/tests
      - name: Stop containers
        run: docker-compose down
