name: Run Tests

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d
      - name: Run tests
        run: docker exec -t devel_dashboard pytest -v dashboard/tests
      - name: Stop containers
        if: always()
        run: cd containers/devel && docker-compose down
