name: Run tests and update docs

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
    types: [opened, edited]

jobs:

  # build:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Pull pre-existing images
  #       run: cd containers/devel && docker-compose pull
  #     - uses: satackey/action-docker-layer-caching@v0.0.11
  #       continue-on-error: true
  #       with:
  #         key: dashboard-docker-cache-{hash}
  #         restore-keys: dashboard-docker-cache-
  #     - run: cd containers/devel && docker-compose build

  # test:
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: satackey/action-docker-layer-caching@v0.0.11
  #       continue-on-error: true
  #       with:
  #         restore-keys: dashboard-docker-cache-
  #     - name: Start up the dashboard
  #       run: cd containers/devel && docker-compose up -d
  #     - name: Run tests
  #       run: |
  #         docker exec -t devel_dashboard pytest -v dashboard/tests
  #     - name: Stop containers
  #       if: always()
  #       run: cd containers/devel && docker-compose down

  make-docs:
    needs: build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d
      - name: Check paths
        run: docker exec -t devel_dashboard /bin/bash -c "pwd && ls -l"
      - name: Check import works
        run: docker exec -t devel_dashboard /bin/bash -c "python -c 'import dashboard; print(dir(dashboard))'"
      # - name: Build docs
      #   run: docker exec -t devel_dashboard /bin/bash -c "cd dashboard/docs && make html"
      # - name: Deploy docs
      #   uses: JamesIves/github-pages-deploy-action@v4.2.2
      #   with:
      #     branch: gh-pages
      #     folder: docs/html
      - name: Stop containers
        if: always()
        run: cd containers/devel && docker-compose down
