name: Run tests and update docs

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
    types: [opened, edited]

jobs:

  # build:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Pull pre-existing images
  #       run: cd containers/devel && docker-compose pull
  #     - uses: satackey/action-docker-layer-caching@v0.0.11
  #       continue-on-error: true
  #       with:
  #         key: dashboard-docker-cache-{hash}
  #         restore-keys: dashboard-docker-cache-
  #     - run: cd containers/devel && docker-compose build

  # test:
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: satackey/action-docker-layer-caching@v0.0.11
  #       continue-on-error: true
  #       with:
  #         restore-keys: dashboard-docker-cache-
  #     - name: Start up the dashboard
  #       run: cd containers/devel && docker-compose up -d
  #     - name: Run tests
  #       run: |
  #         docker exec -t devel_dashboard pytest -v dashboard/tests
  #     - name: Stop containers
  #       if: always()
  #       run: cd containers/devel && docker-compose down

  make-docs:
    # needs: build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d
      - name: Build docs
        run: docker exec -t devel_dashboard /bin/bash -c "sphinx-build dashboard/docs dashboard/docs/_build"
      - name: Repeat build in case non-deterministic build issue arose in last step
        run: docker exec -t devel_dashboard /bin/bash -c "sphinx-build dashboard/docs dashboard/docs/_build"
      - name: Check the build folder contents in container
        run: docker exec -t devel_dashboard /bin/bash -c "ls -l dashboard/docs/"
      - name: Check the build folder in outside of the compose container
        run: ls -l /dashboard/docs/
      # - name: Add .nojekyll file to build folder
      #   run: touch /dashboard/docs/_build/.nojekyll
      # - name: Deploy docs
      #   uses: JamesIves/github-pages-deploy-action@v4.2.2
      #   with:
      #     branch: gh-pages
      #     folder: docs/_build
      - name: Stop containers
        if: always()
        run: cd containers/devel && docker-compose down
