name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Start up the dashboard
        run: cd containers/devel && docker-compose up -d

      - name: Install requirements
        run: docker exec -t devel_dashboard /bin/bash -c "pip install -r dashboard/test_requirements.txt"

      - name: Run tests
        run: docker exec -t devel_dashboard pytest -v dashboard/tests

      - name: Stop containers
        if: always()
        run: cd containers/devel && docker-compose down